---
collections:
  - name: redhat.satellite

  - name: redhat.rhv

  - name: vmware.vmware_rest
    version: 1.0.1

  - name: ansible.controller

  - name: ansible.netcommon

  - name: azure.azcollection

  - name: ansible.windows

  - name: community.windows

  - name: community.general

  - name: community.vmware
