---
- name: Block for RHV
  block:
    - name: Login to RHV
      redhat.rhv.ovirt_auth:
        hostname: "{{ rhvm_fqdn }}"
        username: "{{ rhvm_user }}"
        password: "{{ rhvm_password }}"
        ca_file: "{{ rhvm_cafile | default(omit) }}"
        insecure: "{{ rhvm_insecure | default(true) }}"

    - name: Stop VM
      redhat.rhv.ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: "{{ item }}"
        state: stopped
        wait: true
      loop: "{{ vm_names }}"

    - name: Delete VM
      redhat.rhv.ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: "{{ item }}"
        state: absent
        wait: true
      loop: "{{ vm_names }}"

  always:
    - name: Logout from RHV
      redhat.rhv.ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
