---

- name: Get VM info
  vmware.vmware_rest.vcenter_vm_info:
    filter_names:
      - "{{ item }}"
    vcenter_validate_certs: false
  register: vm_info

- name: Ensure IP is defined
  vmware.vmware_rest.vcenter_vm_guest_identity_info:
    vm: "{{ vm_info.value[0].vm }}"
    vcenter_validate_certs: false
  register: vm_full_info
  until: vm_full_info.value.ip_address is defined
  retries: 10
  delay: 2
