---

- name: Get VM info
  vmware.vmware.guest_info:
    name: "{{ item }}"
    datacenter: "Shadowman-DC"
    validate_certs: false
  register: vm_info
  until: vm_info.guests[0].identity.ip_address is defined
  retries: 10
  delay: 2

- name: Add Linux hosts to just_created group
  ansible.builtin.add_host:
    hostname: "{{ item }}"
    ansible_host: "{{ vm_info.guests[0].identity.ip_address }}"
    groups: just_created
