---
- name: Remove VM on RHV
  hosts: "{{ vm_name | default('none') }}"
  gather_facts: false

  vars:
    shadowman_provision_hypervisor: "RHV"

  roles:
    - shadowman_deprovision
    - shadowman_soft_delete
