---
- name: Create VM on RHV
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    shadowman_provision_hypervisor: RHV

  roles:
    - shadowman_provision

- name: Perform hostname Set and reset agent to get FQDN on Linux
  hosts: just_created
  gather_facts: false

  vars:
    shadowman_provision_hypervisor: RHV

  roles:
    - shadowman_hostnameset
