---
- name: Sync Inventory
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    inventory_source_name: "{{ shadowman_provision_hypervisor}} Production"
    inventory_name: "Shadowman Production"
    
  roles:
    - shadowman_inventory_collection