---
- name: Get all newly created Linux hosts
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Add hosts to to be able to set hostname
      ansible.builtin.include_role:
        name: shadowman_provision
        tasks_from: vmware_wait

- name: Perform hostname Set
  hosts: just_created
  gather_facts: false

  vars:
    shadowman_provision_hypervisor: "VMWare"

  roles:
    - shadowman_hostnameset
