---
- name: Create VM
  hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - shadowman_provision

- name: Get IP and set hostname if needed
  hosts: just_created
  gather_facts: false

  roles:
    - shadowman_hostnameset
