---
- name: VM Create for Template
  ansible.builtin.include_tasks: rhv_vm_templatevmcreate.yml
  when: shadowman_template == "createvm"

- name: Create Template
  ansible.builtin.include_tasks: rhv_vm_templatecreate.yml
  when: shadowman_template == "createtemplate"
