---
- name: Move Windows host to workgroup to disable in AD
  microsoft.ad.membership:
    workgroup_name: removegroup
    domain_admin_user: "{{ domainuser }}"
    domain_admin_password: "{{ domainpassword }}"
    state: workgroup
  ignore_errors: true # ignore due to WINRM issues
  when: ansible_host != ip_addr

- name: Remove Windows host from AD
  when: ansible_host != ip_addr
  block:
    - name: Delete Windows host from AD
      microsoft.ad.computer:
        name: "{{ fqdn.split('.')[0] }}"
        state: absent
      delegate_to: dc01.ad.shadowman.dev
  rescue:
    - name: Retry Delete Windows host from AD due to WINRM
      microsoft.ad.computer:
        name: "{{ fqdn.split('.')[0] }}"
        state: absent
      delegate_to: dc01.ad.shadowman.dev
