---

# - name: Remove RHV VM
#   ansible.builtin.include_tasks: rhv_vm_remove.yml
#   when: shadowman_provision_hypervisor == "RHV"

- name: Remove VMWare VM
  ansible.builtin.include_tasks: vmware_vm_remove.yml
  when: shadowman_provision_hypervisor == "VMWare"

- name: Remove Azure VM
  ansible.builtin.include_tasks: azure_vm_remove.yml
  when: shadowman_provision_hypervisor == "Azure"

- name: Remove AWS VM
  ansible.builtin.include_tasks: aws_vm_remove.yml
  when: shadowman_provision_hypervisor == "AWS"

- name: Remove OCP VM
  ansible.builtin.include_tasks: ocpv_vm_remove.yml
  when: shadowman_provision_hypervisor == "OCPV"
