---
- name: Look up the VM in the inventory
  vmware.vmware_rest.vcenter_vm_info:
    filter_names:
      - "{{ inventory_hostname }}"
    vcenter_validate_certs: false
  register: search_result
  delegate_to: localhost

- name: Turn off VM
  vmware.vmware.vm_powerstate:
    moid: '{{ search_result.value[0].vm }}'
    datacenter: "Shadowman-DC"
    state: powered-off
    validate_certs: false
  delegate_to: localhost

- name: Delete some VM
  vmware.vmware.vm:
    state: absent
    moid: '{{ search_result.value[0].vm }}'
    validate_certs: false
  delegate_to: localhost
