---
- name: Look up the VM in the inventory
  vmware.vmware_rest.vcenter_vm_info:
    filter_names:
      - "{{ inventory_hostname }}"
    vcenter_validate_certs: false
  register: search_result
  delegate_to: localhost

- name: Turn off VM
  vmware.vmware_rest.vcenter_vm_power:
    state: stop
    vm: "{{ search_result.value[0].vm }}"
    vcenter_validate_certs: false
  delegate_to: localhost

- name: Delete some VM
  vmware.vmware_rest.vcenter_vm:
    state: absent
    vm: "{{ search_result.value[0].vm }}"
    vcenter_validate_certs: false
  delegate_to: localhost
