---

- name: Set base URL for hosts
  ansible.builtin.set_fact:
    __base_url: "https://{{ lookup('ansible.builtin.env', 'CONTROLLER_HOST') }}/api/controller/v2/hosts?page_size=200"

- name: "Get hosts total count"
  ansible.builtin.uri:
    url: "{{ __base_url }}"
    method: GET
    return_content: true
    status_code: 200
    body_format: json
    headers:
      Authorization: "Bearer {{ aap_token.token }}"
  register: __host_inv_hosts_count

- name: Set expected number of pages
  ansible.builtin.set_fact:
    __pages: "{{ (__host_inv_hosts_count.json.count // 200) + 1 }}"

- name: Show expected number of hosts and pages
  ansible.builtin.debug:
    msg: "Expecting {{ __host_inv_hosts_count.json.count }} hosts across {{ __pages }} pages"

- name: Create a list of hosts URLs
  ansible.builtin.set_fact:
    __host_inv_hosts_url_list: "{{ range(1, __pages | int + 1) | map('regex_replace', '^', __base_url2) | list }}"
  vars:
    __base_url2: "{{ __base_url }}&page="

- name: "Get hosts"
  ansible.builtin.uri:
    url: "{{ item }}"
    method: GET
    return_content: true
    status_code: 200
    body_format: json
    headers:
      Authorization: "Bearer {{ aap_token.token }}"
  loop: "{{ __host_inv_hosts_url_list }}"
  loop_control:
    label: "{{ item }}"
  until: __host_inv_hosts.status == 200
  retries: 1
  delay: 3
  register: __host_inv_hosts

- name: Update hosts list
  ansible.builtin.set_fact:
    __host_inv_hosts_list: >-
      {{
        __host_inv_hosts_list | default([]) +
        item.json.results |
        map(attribute='name') |
        flatten |
        list
      }}
  loop: "{{ __host_inv_hosts.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Assert host count matches
  ansible.builtin.assert:
    that:
      - __host_inv_hosts_count.json.count == __host_inv_hosts_list | length
    success_msg: "Host count matches: {{ __host_inv_hosts_count.json.count }} == {{ __host_inv_hosts_list | length }}"
    fail_msg: "Host count mismatch: {{ __host_inv_hosts_count.json.count }} != {{ __host_inv_hosts_list | length }}"

- name: Clean up duplicates from hosts list
  ansible.builtin.set_fact:
    __host_inv_hosts_list: >-
      {{
        __host_inv_hosts_list |
        unique
      }}

- name: Show resulting unique host count
  ansible.builtin.debug:
    msg: "Unique hosts: {{ __host_inv_hosts_list | length }}"
